### ISSUE TITLE
ep3 : большой рефакторинг

### ISSUE THREAD

**Issue by avasyukov** [NikolayMorgunov/pandas-lab#1]
На третий эпизод точно нужно навести pandas-овый фэн-шуй с `groupby`, `merge` и всем чем положено.
*(Первые два эпизода тоже сильно просятся на рефакторинг, но при жёсткой нехватке времени их можно оставить как есть.)*

**Comment by NikolayMorgunov** [comment]
Спасибо, все исправил.
